# Generated by Django 4.0.6 on 2022-07-21 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_rename_cakes_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
            ],
        ),
    ]
