# Generated by Django 4.0.6 on 2022-07-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alter_cake_name_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='cake',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
    ]
