# Generated by Django 4.0.6 on 2022-07-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
