# Generated by Django 4.0.6 on 2022-07-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0010_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
