# Generated by Django 4.0.6 on 2022-07-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0011_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('text', models.TextField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.filling')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.product')),
            ],
        ),
    ]
