# Generated by Django 4.0.6 on 2022-07-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
