# Generated by Django 4.0.6 on 2022-07-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0013_remove_review_cake_remove_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='filling',
        ),
    ]
