# Generated by Django 4.0.6 on 2022-07-25 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0014_remove_review_filling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.IntegerField()),
                ('phone', models.IntegerField(default=80291111111, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(11)])),
                ('text', models.TextField()),
            ],
        ),
    ]
