# Generated by Django 4.0.6 on 2022-07-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
