# Generated by Django 4.0.6 on 2022-07-25 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0018_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('date', models.DateField()),
                ('weight', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField(max_length=255)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.filling')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.product')),
            ],
        ),
    ]
