# Generated by Django 4.0.6 on 2022-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
